### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by miketdollar**
Simple change to test the CI pipeline script.

### CODE REVIEW

**Review by erikrj — APPROVED** [review]

**Review by nrconan99 — APPROVED** [review]

**Review by nrconan99 — APPROVED** [review]

**Review by nrconan99 — APPROVED** [review]

**Review by nrconan99 — APPROVED** [review]

**Review by nrconan99 — APPROVED** [review]

**Comment by nrconan99** [comment]
Merge failed

**Comment by nrconan99** [comment]
Build failed

**Review by nrconan99 — APPROVED** [review]

**Comment by nrconan99** [comment]
Merge failed

**Comment by nrconan99** [comment]
Build failed

**Review by nrconan99 — APPROVED** [review]

**Pull request merged**
